# Generated by Django 5.0.1 on 2024-01-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Publisher name', max_length=50)),
                ('website', models.URLField(help_text='Publisher website')),
                ('email', models.EmailField(help_text='Publisher email', max_length=254)),
            ],
        ),
    ]
