# Generated by Django 5.0.1 on 2024-02-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_book_contributors_alter_book_publisher_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="text",
            new_name="content",
        ),
    ]
